on: [push]
       

jobs:
  build: 
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
          dotnet-quality: 'ga'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore 
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --no-restore --verbosity normal
